### ISSUE TITLE
WARN install No prebuilt binaries found (target=10.15.3 runtime=node arch=x64 platform=win32)

### ISSUE THREAD

**Issue by peterennis** [JamesKyburz/fontello-server#123]
I am trying to build this with Docker Windows Desktop.
Setup configured for Linux containers.

I get this error no matter what dependencies are updated.

I would like to have a local fontello server for font testing/development.

Suggestions welcome.

```
Microsoft Windows [Version 10.0.17763.503]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\ae\fontello-server>npm i
npm WARN deprecated debug@2.6.6: invalid release
npm WARN deprecated bourne@1.1.2: This module has moved and is now available at @hapi/bourne. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

> leveldown@1.7.2 install C:\ae\fontello-server\node_modules\level\node_modules\leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.15.3 runtime=node arch=x64 platform=win32)

C:\ae\fontello-server\node_modules\level\node_modules\leveldown>if not defined npm_config_node_gyp (node "C:\Users\peter\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\peter\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\peter\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\peter\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\ae\fontello-server\node_modules\level\node_modules\leveldown
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.7.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@1.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\peter\AppData\Roaming\npm-cache\_logs\2019-06-12T04_01_24_618Z-debug.log

C:\ae\fontello-server>
```

**Comment by JamesKyburz** [comment]
I think this error is caused by trying to compile the version of leveldown using node 10.

Unfortunately this can't be fixed quickly because some of the used dependencies use the version of leveldown that won't work with node 10 :/

I suggest using the docker image `jameskyburz/fontello-server:v1.1.29` which uses `node 8`

**Comment by peterennis** [comment]
Thanks for the info. I will try that and report back any issues.
